<a href="https://colab.research.google.com/github/241541601038-glitch/JALIZ/blob/main/Ex07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded=files.upload()

Saving two.jpg to two.jpg


In [6]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
img1 = cv2.imread("two.jpg", cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread("two.jpg", cv2.IMREAD_GRAYSCALE)

if img1 is None or img2 is None:

 raise FileNotFoundError("One of the images was not found. Check the file paths.")

orb = cv2.ORB_create(5000)
keypoints1, descriptors1 = orb.detectAndCompute(img1, None)
keypoints2, descriptors2 = orb.detectAndCompute(img2, None)
bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
matches = bf.match(descriptors1, descriptors2)
matches = sorted(matches, key=lambda x: x.distance)
pts1 = np.float32([keypoints1[m.queryIdx].pt
for m in matches])
pts2 = np.float32([keypoints2[m.trainIdx].pt
for  m in matches])
F,mask = cv2.findFundamentalMat(pts1, pts2, cv2.FM_RANSAC)
print("Fundamental Matrix:")
print(F)

Fundamental Matrix:
[[ 1.17241516e-20 -1.52423025e-05  9.03626442e-03]
 [ 1.52423025e-05 -3.66379737e-22 -1.48115712e-02]
 [-9.03626442e-03  1.48115712e-02  7.99360578e-15]]
